# Generated by Django 3.1.5 on 2021-03-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
