# Generated by Django 3.1.5 on 2021-03-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_reviews', '0002_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
