# Generated by Django 3.1.5 on 2021-03-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_reviews', '0009_auto_20210329_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
